version: '3'
services:
  grafana:
    image: grafana/grafana:7.3.2
    container_name: grafana
    restart: unless-stopped
    environment:
      TZ: "Asia/Kolkata"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,simpod-json-datasource,marcusolsson-json-datasource"
    volumes:
      - /opt/docker/grafana/:/var/lib/grafana
      - /opt/docker/grafana/:/etc/grafana
    ports:
      - 3000:3000
