version: '3'
services:
  grafana:
    image: grafana/grafana:8.1.3
    container_name: grafana
    restart: unless-stopped
    environment:
      TZ: "Asia/Kolkata"
    volumes:
      - /opt/docker/grafana/:/var/lib/grafana
      - /opt/docker/grafana/conf:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
