version: '3'
services:
  grafana:
    image: grafana/grafana:8.0.5
    container_name: grafana
    restart: unless-stopped
    environment:
      TZ: "Asia/Kolkata"
    volumes:
      - /opt/docker/grafana/:/var/lib/grafana
    ports:
      - 3000:3000
